cache:
    enabled: true
    size: 3000
    expirationMinutes: 10  # 10 minutes
    ResetTtlPerAccess: false


aniList:
    baseUrl: https://graphql.anilist.co
    options:
        isAdult: false
    query:
        media: |
            id
            title {
                romaji
                english
                native
            }
            genres
            tags {
                name
            }
            description
            type
            format
            coverImage {
                large
            }
            status
            averageScore
            volumes
            chapters
            episodes
            isAdult
        relations: |
            relations {
                edges {
                    relationType
                    node {
                        id
                        title {
                            romaji
                            english
                        }
                        genres 
                        description
                        type
                        coverImage {
                            extraLarge
                        }
                        volumes
                        chapters
                        episodes
                        status
                        averageScore
                        isAdult
                    }
                }
            }
        recommendations: |
            recommendations {
                edges {
                    node {
                        id
                        mediaRecommendation {
                            id
                            title {
                                romaji
                                english
                            }
                            genres 
                            description
                            type
                            coverImage {
                                extraLarge
                            }
                            volumes
                            chapters
                            episodes
                            status
                            averageScore
                            isAdult
                        }
                        rating
                    }
                }
            }
        characters: |
            characters {    
                edges {
                    role
                    node {
                        id
                        name {
                            full
                        }
                        image {
                            large
                        }
                    }
                }
            }